import { useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, BookOpenCheck, LockKeyhole, ShieldCheck, UserRound } from 'lucide-react';
import { IoSchoolOutline } from 'react-icons/io5';
import { useAuth } from '../contexts/AuthContext';
import { Button, Input } from '../components/ui';

export function LoginPage() {
  const [username, setUsername] = useState('admin'); const [password, setPassword] = useState('admin123456');
  const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  const { login } = useAuth(); const navigate = useNavigate();
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setSubmitting(true); try { await login(username, password); navigate('/'); } catch (e) { setError(e instanceof Error ? e.message : '登录失败，请稍后重试'); } finally { setSubmitting(false); } };
  return <div className="grid min-h-screen lg:grid-cols-[1.08fr_.92fr]"><section className="relative hidden overflow-hidden bg-[#092e5c] p-14 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-28 -top-28 h-96 w-96 rounded-full bg-sky-400/10"/><div className="absolute bottom-0 left-1/3 h-80 w-80 rounded-full bg-brand-500/10"/><div className="relative flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white/10 text-sky-300"><IoSchoolOutline size={28}/></span><div><div className="text-xl font-bold">乐学英语</div><div className="text-xs tracking-[.2em] text-slate-300">ADMIN CONSOLE</div></div></div><div className="relative max-w-xl"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs text-sky-200"><ShieldCheck size={14}/>专业、安全、高效</span><h1 className="mt-6 text-5xl font-bold leading-tight">让教育管理<br/><span className="text-sky-300">更简单、更智能</span></h1><p className="mt-5 max-w-lg text-lg leading-relaxed text-slate-300">统一管理学习内容、题库考试、用户会员与 AI 服务，用数据驱动每一次教学决策。</p><div className="mt-10 flex gap-8 text-sm text-slate-300"><span className="flex items-center gap-2"><BookOpenCheck size={18} className="text-sky-300"/>内容精细运营</span><span className="flex items-center gap-2"><ShieldCheck size={18} className="text-sky-300"/>全链路审计</span></div></div><p className="relative text-xs text-slate-500">© 2026 乐学英语 · 教育管理平台</p></section><section className="flex items-center justify-center bg-white p-6"><div className="w-full max-w-md"><div className="mb-10 lg:hidden"><span className="flex items-center gap-2 text-xl font-bold text-brand-900"><IoSchoolOutline size={28}/>乐学英语</span></div><p className="text-sm font-semibold text-brand-600">欢迎回来</p><h2 className="mt-2 text-3xl font-bold text-slate-900">登录管理后台</h2><p className="mt-2 text-sm text-slate-500">请输入管理员账号继续访问控制台</p><form className="mt-8 space-y-5" onSubmit={submit}><label className="block"><span className="field-label">用户名</span><div className="relative"><UserRound size={17} className="absolute left-3 top-3 text-slate-400"/><Input className="pl-10" value={username} onChange={(e)=>setUsername(e.target.value)} autoComplete="username" required/></div></label><label className="block"><span className="field-label">密码</span><div className="relative"><LockKeyhole size={17} className="absolute left-3 top-3 text-slate-400"/><Input className="pl-10" type="password" value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete="current-password" required/></div></label>{error && <p className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<Button className="w-full" type="submit" disabled={submitting}>{submitting ? '正在验证…' : '登录'}<ArrowRight size={17}/></Button></form><div className="mt-8 rounded-xl border bg-slate-50 p-4 text-xs text-slate-500"><strong className="text-slate-700">开发环境默认账号</strong><p className="mt-1 font-mono">admin / admin123456</p></div></div></section></div>;
}
